- include: build.yaml

- name: Ensure group that "ftpusers" exists
  become: yes
  ansible.builtin.group:
    gid: 2121
    name: ftpusers
    state: present

- name: Add proftpd server user "ftpusers"
  become: yes
  user:
    uid: 2121
    name: ftpusers
    groups: ftpusers
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "ftpusers nologin user"
    state: present

- name: Check previous proftpd installation
  stat:
    path: /opt/proftpd
  register: proftpd_stat

- name: Backup previous proftpd version
  become: yes
  ansible.builtin.shell:
    cmd: "mv /opt/proftpd /opt/proftpd-{{ ansible_date_time.epoch }}"
  when: proftpd_stat.stat.exists

- name: Install proftpd to {{ inventory_hostname }}
  become: yes
  make:
    chdir: /tmp/proftpd-1.3.7f
    target: install

- name: Copy proftpd unit file for systemctl
  become: yes
  ansible.builtin.copy:
    src: proftpd.service
    dest: /usr/lib/systemd/system/proftpd.service

- name: Copy ssh host RSA key to proftpd config dir
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/ssh/ssh_host_rsa_key
    dest: /opt/proftpd/etc/ssh_host_rsa_key
    mode: '0600'

- name: Copy custom proftp config
  become: yes
  ansible.builtin.template:
    src: proftpd.conf.j2
    dest: /opt/proftpd/etc/proftpd.conf
    owner: root
    group: root
    mode: '0655'

- name: Create a log directory for proftpd
  become: yes
  ansible.builtin.file:
    path: /var/log/proftpd
    state: directory

- name: Create a directory for ftp-data
  become: yes
  ansible.builtin.file:
    path: /data1/ftp-data
    state: directory
    mode: '0755'

- name: Create a symbolic link of ftp-data in root
  become: yes
  ansible.builtin.file:
    src: /data1/ftp-data
    dest: /ftp-data
    owner: root
    group: root
    state: link

- name: Create ftp server work directories
  become: yes
  ansible.builtin.file:
    path: "/ftp-data/{{ item }}"
    owner: ftpusers
    group: ftpusers
    state: directory
    mode: '0755'
  with_items:
    - etc
    - home

- name: Copy ftp manipulation scripts
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/ftp-data/etc/{{ item }}"
    owner: ftpusers
    group: ftpusers
    mode: a+x
  with_items:
    - adduser.sh
    - changepassword.sh

- name: Create users database /ftp-data/etc/ftpd.passwd
  become: yes
  ansible.builtin.expect:
    command: ./adduser.sh anonymous
    chdir: /ftp-data/etc
    responses:
      (?i)Password: anonymous
